name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: "composite"
  steps:
    - run: echo "hi"
      shell: bash
    - run: echo "hey"
      shell: bash
    - uses: actions/checkout@v2
      if: ${{ github.ref == 'refs/heads/main' }}
    - uses: actions/setup-node@v2
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        node-version: 12
